tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "sanemat/font"

brew "asdf"
brew "ca-certificates"
brew "fontforge"
brew "git"
brew "gnupg"
brew "openssl@3"
brew "python@3.9"
brew "readline", link: true
brew "sanemat/font/ricty"
brew "starship"
brew "stow"
brew "tree"
brew "zsh"

cask "alfred"
#cask "brave-browser"
#cask "cheatsheet"
#cask "clipy"
#cask "deepl"
#cask "discord"
cask "font-hackgen-nerd"
#cask "google-japanese-ime"
#cask "google-chrome"
#cask "iceberg"
#cask "kindle"
#cask "nordvpn"
#cask "nordpass"
#cask "slack"
#cask "stack"
#cask "visual-studio-code"
