tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "sanemat/font"

#brew "ca-certificates"
#brew "readline", link: true
brew "asdf"
#brew "python@3.9"
#brew "cairo"
#brew "fontforge"
brew "git"
#brew "gnupg"
#brew "openssl@3"
#brew "rbenv"
brew "tree"
brew "zsh"
brew "sanemat/font/ricty"

cask "alfred"
#cask "brave-browser"
#cask "cheatsheet"
#cask "clipy"
#cask "deepl"
#cask "discord"
#cask "google-japanese-ime"
#cask "google-chrome"
#cask "kindle"
#cask "nordvpn"
#cask "nordpass"
#cask "slack"
#cask "stack"
#cask "visual-studio-code"
